# Generated by Django 2.2.3 on 2019-10-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=10)),
                ('headsign', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.Stop')),
            ],
        ),
    ]
