# Generated by Django 2.2.3 on 2019-10-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0002_auto_20191026_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departure',
            unique_together=set(),
        ),
    ]
