# Generated by Django 2.2.3 on 2019-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0003_auto_20191026_1158'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departure',
            name='unique_departure',
        ),
        migrations.AddConstraint(
            model_name='departure',
            constraint=models.UniqueConstraint(fields=('line', 'headsign', 'timestamp'), name='unique_departure'),
        ),
    ]
