# Generated by Django 2.2.3 on 2019-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('given_id', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('lines', models.CharField(max_length=50)),
            ],
        ),
    ]
