# Generated by Django 2.2.3 on 2019-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_bikes', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
