# Generated by Django 2.2.3 on 2019-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerack',
            name='free_racks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bikerack',
            name='free_bikes',
            field=models.IntegerField(default=0),
        ),
    ]
