# Generated by Django 2.2.3 on 2019-10-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20191022_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikerack',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='bikerack',
            old_name='lon',
            new_name='longitude',
        ),
    ]
