# Generated by Django 2.2.3 on 2019-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20191022_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikerack',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bikerack',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
